imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    validation:      { enable_annotations: true }
    default_locale:  "fr"
    fragments:       ~
    http_method_override: true
    assets: ~
    property_info:
      enabled: true

    # This is required for ewz_recaptcha
    templating:
      engines: ['twig']

twig:
    debug:            "%kernel.debug%"
    strict_variables: false
    form_themes:
#        # Symfony's core form themes, last one if default one
        - "bootstrap_3_layout.html.twig"
#        - "bootstrap_3_horizontal_layout.html.twig"

#doctrine:
#    dbal:
#        default_connection: default
#        connections:
#            default:
#                logging: "%kernel.debug%"
#                profiling: "%kernel.debug%"
#    orm:
#        # @todo cannot disable this until the cache warmer isn't full restored
#        auto_generate_proxy_classes: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true